
services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
    - ./client:/myapp
    - /myapp/node_modules
    ports:
    - "3000:3000"
    depends_on:
    - server
    restart: always


  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
    - ./server:/myapp
    - /myapp/node_modules
    expose:
    - 3001
    env_file:
      - ./server/.env
    restart: always

# mongo:
#   image: mongo:latest
#   expose:
#   - 27017
#   volumes:
#   - ./data:/data/db
#   restart: always
  